on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '20.6'
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm test
        if: ${{ ! failure() }}
