on: push
jobs:
  check_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '20.6'
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check
        if: ${{ ! failure() }}
      - name: Build
        run: npm run build
        if: ${{ ! failure() }}
      - name: Create artifact
        run: |
          rm -rf node_modules
          tar -cf bread-framework.tar.gz ./*
        if: ${{ ! failure() }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bread-framework.tar.gz
          path: bread-framework.tar.gz
        if: ${{ ! failure() }}
